const MAX_SPACES_PER_USER = 4;
const MAX_UNITS_PER_SPACE = 4;
const MAX_UNITS_PER_UNIT = 3;

const LAUNCH_HEADER_BDRS = 16.8; // max for 48 height (16.8 * 1.25 + 3), see Corners
const LAUNCH_PAPER_BDRS = 32;
const LAUNCH_CARD_BDRS = 24;

export {
  MAX_SPACES_PER_USER,
  MAX_UNITS_PER_SPACE,
  MAX_UNITS_PER_UNIT,
  LAUNCH_PAPER_BDRS,
  LAUNCH_HEADER_BDRS,
  LAUNCH_CARD_BDRS,
};
