const MAX_SPACES_PER_USER = 4;
const MAX_UNITS_PER_SPACE = 4;
const MAX_UNITS_PER_UNIT = 3;

const LAUNCH_PAPER_BDRS = 20;

export { MAX_SPACES_PER_USER, MAX_UNITS_PER_SPACE, MAX_UNITS_PER_UNIT, LAUNCH_PAPER_BDRS };
