// import type { ControlCaption } from './components/Toolbar';

const DEFAULT_TEST_ID = '@launch-ui/richtext';

// const DEFAULT_CAPTIONS: Record<ControlCaption, string> = {
const DEFAULT_CAPTIONS: Record<string, string> = {
  insertTableOfContent: 'Содержание',
  h1: 'Заголовок 1',
  h2: 'Заголовок 2',
  h3: 'Заголовок 3',
  h4: 'Заголовок 4',
  h5: 'Заголовок 5',
  h6: 'Заголовок 6',
  paragraph: 'Текст',
  bulletList: 'Маркированный',
  orderedList: 'Нумерованный',
  checkbox: 'Список задач',
  hr: 'Разделитель',
  expand: 'Раскрывающийся блок',
  fragment: 'Выборка',
  include: 'Вставить страницу или выборку',
  blockquote: 'Цитата',
  codeBlock: 'Блок кода',
  left: 'По левому краю',
  right: 'По правому краю',
  center: 'По центру',
  justify: 'По ширине',
  code: 'Код',
  inlineComment: 'Комментировать',
  bold: 'Жирный',
  italic: 'Курсив',
  strike: 'Зачеркнутый',
  underline: 'Подчеркнутый',
  tableInsert: 'Вставить таблицу',
  tableDelete: 'Удалить таблицу',
  addColumnBefore: 'Столбец слева',
  addColumnAfter: 'Столбец справа',
  deleteColumn: 'Удалить столбец',
  addRowBefore: 'Строка сверху',
  addRowAfter: 'Строка снизу',
  deleteRow: 'Удалить строку',
  mergeCells: 'Объединить ячейки',
  splitCell: 'Разделить ячейку',
  toggleHeaderColumn: 'Столбец-заголовок',
  toggleHeaderRow: 'Строка-заголовок',
  redColor: 'Красный',
  greenColor: 'Зеленый',
  lightBlueColor: 'Светло-синий',
  blackColor: 'Черный',
  lightGreyColor: 'Светло-серый',
  blueColor: 'Голубой',
  darkOrangeColor: 'Темно-оранжевый',
  lightOrangeColor: 'Светло-оранжевый',
  purpleColor: 'Фиолетовый',
  redColorBackground: 'Красный фон',
  greenColorBackground: 'Зеленый фон',
  lightBlueColorBackground: 'Светло-синий фон',
  blackColorBackground: 'Черный фон',
  lightGreyColorBackground: 'Светло-серый фон',
  blueColorBackground: 'Голубой фон',
  darkOrangeColorBackground: 'Темно-оранжевый фон',
  lightOrangeColorBackground: 'Светло-оранжевый фон',
  purpleColorBackground: 'Фиолетовый фон',
  defaultColor: 'Черный',
  textColorClear: 'Очистить цвет текста',
  textHighlightClear: 'Очистить цвет фона',
  textColorAndHighlightClear: 'Очистить цвет текста и фона',
  chooseAttachment: 'Вложение',
  insertDrawIo: 'Схема DrawIO',
  insertPlantUML: 'Схема PlantUML',
  insertBlocksGrid: 'Вставить разделы',
  deleteBlocksGrid: 'Удалить разделы',
  undo: 'Отменить',
  redo: 'Востановить',
  addTab: 'Создать отступ',
  removeTab: 'Удалить отступ',
  colorFill: 'Залить ячейку таблицы',
  colorFillLightGreen: 'Светло-зеленый',
  colorFillLightYellow: 'Светло-желтый ',
  colorFillLightRed: 'Светло-красный',
  colorFillLightTurquoise: 'Светло бирюзовый',
  colorFillLightBlue: 'Светло-синий',
  colorFillModerateGray: 'Умерено серый',
  colorFillLightGray: 'Светло-серый',
  colorFillNoFill: 'Без заливки',
};

const TOOLBAR_HEIGHT = 48;

export { DEFAULT_TEST_ID, DEFAULT_CAPTIONS, TOOLBAR_HEIGHT };
